### ISSUE TITLE
Intregrate into mio

### ISSUE THREAD

**Issue by jean-airoldie** [jean-airoldie/libzmq-rs#16]
To allow polling via [`mio`], the sockets must implement [`Evented`]. There a two ways to do so:
* Implement [`EventedFd`] using the zmq_poller file descriptor, which is currently blocked by https://github.com/zeromq/libzmq/issues/2941
* Implement via the registration API, which seem to be [destined for removal](https://github.com/carllerche/mio/issues/907)

The first one is clearly the better option.

[`mio`]: https://github.com/carllerche/mio
[`Evented`]: https://carllerche.github.io/mio/mio/event/trait.Evented.html
[`EventedFd`]: https://carllerche.github.io/mio/mio/unix/struct.EventedFd.html

**Comment by jean-airoldie** [comment]
I wrote this [PR to libzmq](https://github.com/zeromq/libzmq/pull/3484) which will allow to get a `RawFd` associated with the thread-safe socket types. I'll work on integrating into mio.

**Comment by jean-airoldie** [comment]
My initial implementation seem to work but reduces performance by 5X. I filled an issue to see where I went wrong.

**Comment by jean-airoldie** [comment]
From my understanding, this might be a fundamental limitation of `libzmw`. Indeed libzmq keeps track of multiple connections, and therefore file descriptors under the hood. This means that the only way this API would work is if a single file descriptor (that is cloned via [dup2](https://linux.die.net/man/2/dup2)) is used. Then we could effectively poll this single file descriptor. I don't know if that would even work.

**Comment by skeet70** [comment]
Should this be reopened? It seems like from the discussion on cetra3/tmq#6 that this is possible somehow?

**Comment by jean-airoldie** [comment]
From what I recall the tricky part is that the Poller doesn't wakeup when a socket gets closed (https://github.com/zeromq/libzmq/issues/3592). So you would need a way to detect when a socket gets closed and forward it to the Poller somehow (maybe a dedicated socket that receives a message when a socket is closed would work).

It's probably possible but really tricky & unsafe and I'm not interested in spending time on it.
